services:
  # Development services
  postgres:
    image: pgvector/pgvector:pg16
    restart: unless-stopped
    expose:
      - '5432'
    environment:
      POSTGRES_USER: postgres
      POSTGRES_DB: kebapp
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    volumes:
      - kebapp_data:/var/lib/postgresql/data
    networks:
      - kebapp-network

  server:
    image: kebapp-server:latest
    restart: unless-stopped
    expose:
      - '8080'
    depends_on:
      - postgres
    environment:
      - SERVERPOD_RUNMODE=production
    networks:
      - kebapp-network

volumes:
  kebapp_data:

networks:
  kebapp-network:
    external: true
    name: ${DOCKER_NETWORK}
