name: kebapp_server
description: Starting point for a Serverpod server.
# version: 1.0.0
# homepage: https://www.example.com

environment:
  sdk: '>=3.5.0 <4.0.0'

dependencies:
  serverpod: 2.9.2
  serverpod_auth_server: 2.9.2

dev_dependencies:
  lints: '>=6.0.0'
  test: '^1.28.0'
  serverpod_test: 2.9.2
